swagger: "2.0"

host: "localhost:9000"

schemes: [ http ]

info:
  version: "1.0.0"
  title: money manager


definitions:
  Status:
    description: a simple service status
    required:
      - status
    properties:
      status:
        type: string
  Transaction:
    description: a single event involving money
    required:
      - id
      - postedDate
      - payee
      - amount
      - note
      - allocationId
    properties:
      id:
        type: string
      postedDate:
        type: string
        format: timestamp
      payee:
        type: string
      amount:
        type: integer
        format: int32
      note:
        type: string
      allocationId:
        description: the id of the goal or budget this transaction is associated with
        type: integer
        format: int32
  PagedTransactions:
    description: a page of transactions
    required:
      - transactions
    properties:
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"
      prev:
        type: string
  Goal:
    required:
      - id
      - name
      - saved
      - weight
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      saved:
        type: integer
        format: int32
      weight:
        type: integer
        format: int32
      cap:
        type: integer
        format: int32
  GoalBody:
    required:
      - name
      - saved
      - weight
    properties:
      name:
        type: string
      saved:
        type: integer
        format: int32
      weight:
        type: integer
        format: int32
      cap:
        type: integer
        format: int32
  Budget:
    required:
      - id
      - name
      - saved
      - amount
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      saved:
        type: integer
        format: int32
      amount:
        type: integer
        format: int32
      cap:
        type: integer
        format: int32
  BudgetBody:
    required:
      - name
      - saved
      - amount
    properties:
      name:
        type: string
      saved:
        type: integer
        format: int32
      amount:
        type: integer
        format: int32
      cap:
        type: integer
        format: int32


paths:
  /ping:
    get:
      description: ping server to check if it's up
      operationId: ping
      responses:
        200:
          description: response indicating server is up
          schema:
            $ref: "#/definitions/Status"
  /allocations/budgets:
    post:
      description: create new budget
      operationId: createBudget
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/BudgetBody"
      responses:
        204:
          description: newly defined budget
          schema:
            $ref: "#/definitions/Budget"
    get:
      description: get a list of all budgets
      operationId: getBudgets
      responses:
        200:
          description: all budgets
          schema:
            type: array
            items:
              $ref: "#/definitions/Budget"
  /allocations/budgets/{budgetId}:
    post:
      description: update existing budget
      operationId: updateBudget
      parameters:
      - in: path
        name: budgetId
        required: true
        type: integer
        format: int32
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/BudgetBody"
      responses:
        200:
          description: updated budget
          schema:
            $ref: "#/definitions/Budget"
  /allocations/goals:
    post:
      description: create a new goal
      operationId: createGoal
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/GoalBody"
      responses:
        204:
          description: newly defined goal
          schema:
            $ref: "#/definitions/Goal"
    get:
      description: get a list of all goals
      operationId: getGoals
      responses:
        200:
          description: all goals
          schema:
            type: array
            items:
              $ref: "#/definitions/Goal"
  /allocations/goals/{goalId}:
    post:
      description: update existing goal
      operationId: updateGoal
      parameters:
      - in: path
        name: goalId
        required: true
        type: integer
        format: int32
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/GoalBody"
      responses:
        200:
          description: updated goal
          schema:
            $ref: "#/definitions/Goal"
  /transactions:
    get:
      description: get all transactions
      operationId: getTransactions
      parameters:
      - in: query
        name: page
        description: info on requested page.  supplied by PagedTransactions/prev. if not supplied, starts at first page
        type: string
      - in: query
        name: allocationFilter
        type: integer
        format: int32
      - in: query
        name: payeeFilter
        type: string
      responses:
        200:
          description: all transactions
          schema:
            $ref: "#/definitions/PagedTransactions"

